version: 2.1
orbs:
    node: circleci/node@5.0.2

jobs:
    lint_and_test:
        executor: node/default
        tag: '14.19'
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: npm
            - run:
                  command: npm run lint
                  name: Run linter
            - run:
                  command: npm run test
                  name: Run tests

    build:
        executor: node/default
        steps:
            - run:
                  command: npm run build
                  name: Build app
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - .

workflows:
    test_my_app:
        jobs:
            - lint_and_test
            - build:
                  requires:
                      - lint_and_test
