version: 2.1
orbs:
    node: circleci/node@5.1.0

executors:
    my-executor:
        docker:
            - image: 'cimg/base:stable'

jobs:
    test_build_deploy:
        executor: my-executor
        steps:
            - checkout
            - node/install:
                  node-version: '14.19'
            - run: node --version
            - run:
                  command: npm ci
                  name: Npm install
            - run:
                  command: npm run lint
                  name: Run linter
            - run:
                  command: npm run test:ci
                  name: Run tests
            - run:
                  command: npm run build
                  name: Build app

workflows:
    test_my_app:
        jobs:
            - test_build_deploy
